<?php

namespace GEICOM;

use Illuminate\Database\Eloquent\Model;

class action extends Model
{
    const ACTION_ALMOST_ALL = 'ACTION_ALMOST_ALL';
    const ACTION_ALL = 'ACTION_ALL';

    /* ADMINISTRATION */
    const ACTION_ADMIN = 'ACTION_ADMIN';



    //USERS & ROLES


    const ACTION_ADMIN_USER = 'ACTION_ADMIN_USER';
    const ACTION_ADMIN_USER_ACTIVATE_DEACTIVATE = 'ACTION_ADMIN_USER_ACTIVATE_DEACTIVATE';
    const ACTION_ADMIN_USER_DELETE = 'ACTION_ADMIN_USER_DELETE';
    const ACTION_ADMIN_USER_ACTION = 'ACTION_ADMIN_USER_ACTION';
    const ACTION_ADMIN_USER_ACTION_CU = 'ACTION_ADMIN_USER_ACTION_CU';


    //produit et roles
    const ACTION_ADMIN_PRODUIT_ACTION_FIND  = 'ACTION_ADMIN_PRODUIT_ACTION_FIND';
    const ACTION_ADMIN_PRODUIT_ACTION_FIND_BY_M  = 'ACTION_ADMIN_PRODUIT_ACTION_FIND_BY_M';
    const ACTION_ADMIN_STOKS_ACTION_GET_STOCKS_ADMIN = 'ACTION_ADMIN_STOCKS_ACION_GET_STOCKS_ADMIN';

     //BOUTIQUE

    const ACTION_ADMIN_BOUTIQUE_ACTION_BOUTIQUE_LIST = 'ACTION_ADMIN_BOUTIQUE_ACION_BOUTIQUE_LIST_ADMIN';
    const ACTION_ADMIN_BOUTIQUE_ACTION_BOUTIQUE_SET = 'ACTION_ADMIN_BOUTIQUE_ACION_BOUTIQUE_SET_ADMIN';
    const ACTION_ADMIN_USER_ACTION_USER_EDIT_PASS = 'ACTION_ADMIN_USER_ACION_USER_EDIT_PASS';



    //Les logs
    const ACTION_ADMIN_LOGS_ACTION_SHOW_LOG = 'ACTION_ADMIN_LOGS_ACION_SHOW_LOG';

    ///////////////////// Les boutiques

    const ACTION_ADMIN_BOUTIQUE_ACTION_INDEX = 'ACTION_ADMIN_BOUTIQUE_ACION_BOUTIQUE_MANAGEMENT';
    const ACTION_ADMIN_BOUTIQUE_ACTION_STORE = 'ACTION_ADMIN_BOUTIQUE_ACION_STORE_BOUTIQUE';
    const ACTION_ADMIN_BOUTIQUE_ACTION_UPDATE = 'ACTION_ADMIN_BOUTIQUE_ACION_UPDATE_BOUTIQUE';
    const ACTION_ADMIN_BOUTIQUE_ACTION_DELETE = 'ACTION_ADMIN_BOUTIQUE_ACION_MDELETE_BOUTIQUE';

    //Gestion
    const ACTION_ADMIN_MANAGEMENT_ACTION_INDEX = 'ACTION_ADMIN_MANAGEMENT';
    const ACTION_ADMIN_MANAGEMENT_ACTION_GET_INFOS_MAN = 'ACTION_ADMIN_MANAGEMENT_ACION_GET_INFOS_MAN';

// CATEGORIE

    const ACTION_ADMIN_CATEGORIE_ACTION_INDEX = 'ACTION_ADMIN_CATEGORIE_ACION_CATEGORIE_MANAGEMENT';
    const ACTION_ADMIN_CATEGORIE_ACTION_STORE = 'ACTION_ADMIN_CATEGORIE_ACION_STORE_CATEGORIE';
    const ACTION_ADMIN_CATEGORIE_ACTION_UPDATE = 'ACTION_ADMIN_CATEGORIE_ACION_UPDATE_CATEGORIE';
    const ACTION_ADMIN_CATEGORIE_ACTION_DELETE = 'ACTION_ADMIN_CATEGORIE_ACION_MDELETE_CATEGORIE';

    //produits

    const ACTION_ADMIN_PRODUIT_ACTION_INDEX = 'ACTION_ADMIN_PRODUIT_ACION_PRODUIT_MANAGEMENT';
    const ACTION_ADMIN_PRODUIT_ACTION_STORE = 'ACTION_ADMIN_PRODUIT_ACION_STORE_PRODUIT';
    const ACTION_ADMIN_PRODUIT_ACTION_UPDATE = 'ACTION_ADMIN_PRODUIT_ACION_UPDATE_PRODUIT';
    const ACTION_ADMIN_PRODUIT_ACTION_DELETE = 'ACTION_ADMIN_PRODUIT_ACION_MDELETE_PRODUIT';

    const ACTION_ADMIN_PRODUIT_ACTION_INDEX1 = 'ACTION_ADMIN_PRODUIT_ACION_PRODUIT_MANAGEMENT1';
    const ACTION_ADMIN_PRODUIT_ACTION_STORE1 = 'ACTION_ADMIN_PRODUIT_ACION_STORE_PRODUIT1';
    const ACTION_ADMIN_PRODUIT_ACTION_UPDATE1 = 'ACTION_ADMIN_PRODUIT_ACION_UPDATE_PRODUIT1';
    const ACTION_ADMIN_PRODUIT_ACTION_DELETE1 = 'ACTION_ADMIN_PRODUIT_ACION_MDELETE_PRODUIT1';


    // PRODUITS LIES

    const ACTION_ADMIN_PRODUIT_LIES_ACTION_INDEX_LIES = 'ACTION_ADMIN_PRODUIT_LIES_ACION_PRODUIT_LIES_MANAGEMENT';
    const ACTION_ADMIN_PRODUIT_LIES_ACTION_STORE = 'ACTION_ADMIN_PRODUIT_LIES_ACION_STORE_PRODUIT_LIES';
    const ACTION_ADMIN_PRODUIT_LIES_ACTION_DELETE = 'ACTION_ADMIN_PRODUIT_LIES_ACION_MDELETE_PRODUIT_LIES';
    ////////////////////Les pays

    const ACTION_ADMIN_PAYS_ACTION_INDEX = 'ACTION_ADMIN_PAYS_ACION_PAYS_MANAGEMENT';
    const ACTION_ADMIN_PAYS_ACTION_STORE = 'ACTION_ADMIN_PAYS_ACION_STORE_PAYS';
    const ACTION_ADMIN_PAYS_ACTION_UPDATE = 'ACTION_ADMIN_PAYS_ACION_UPDATE_PAYS';
    const ACTION_ADMIN_PAYS_ACTION_DELETE = 'ACTION_ADMIN_PAYS_ACION_MDELETE_PAYS';

    ////////////////////Les personnel

    const ACTION_ADMIN_PERSONNEL_ACTION_INDEX = 'ACTION_ADMIN_PERSONNEL_ACION_PERSONNEL_MANAGEMENT';
    const ACTION_ADMIN_PERSONNEL_ACTION_STORE = 'ACTION_ADMIN_PERSONNEL_ACION_STORE_PERSONNEL';
    const ACTION_ADMIN_PERSONNEL_ACTION_UPDATE = 'ACTION_ADMIN_PERSONNEL_ACION_UPDATE_PERSONNEL';
    const ACTION_ADMIN_PERSONNEL_ACTION_DELETE = 'ACTION_ADMIN_PERSONNEL_ACION_MDELETE_PERSONNEL';

    ///////////////////Les clients

    const ACTION_ADMIN_CLIENT_ACTION_INDEX = 'ACTION_ADMIN_CLIENT_ACION_CLIENT_MANAGEMENT';
    const ACTION_ADMIN_CLIENT_ACTION_STORE = 'ACTION_ADMIN_CLIENT_ACION_STORE_CLIENT';
    const ACTION_ADMIN_CLIENT_ACTION_STORE1 = 'ACTION_ADMIN_CLIENT_ACION_STORE_CLIENT1';
    const ACTION_ADMIN_CLIENT_ACTION_UPDATE = 'ACTION_ADMIN_CLIENT_ACION_UPDATE_CLIENT';
    const ACTION_ADMIN_CLIENT_ACTION_DELETE = 'ACTION_ADMIN_CLIENT_ACION_MDELETE_CLIENT';

    /////////Les fournisseurs
    const ACTION_ADMIN_FOURNISSEUR_ACTION_INDEX = 'ACTION_ADMIN_PFOURNISSEUR_ACION_CLIENT_MANAGEMENT';
    const ACTION_ADMIN_FOURNISSEUR_ACTION_STORE = 'ACTION_ADMIN_FOURNISSEUR_ACION_STORE_FOURNISSEUR';
    const ACTION_ADMIN_FOURNISSEUR_ACTION_STORE1 = 'ACTION_ADMIN_FOURNISSEUR_ACION_STORE_FOURNISSEUR1';
    const ACTION_ADMIN_FOURNISSEUR_ACTION_UPDATE = 'ACTION_ADMIN_FOURNISSEUR_ACION_UPDATE_FOURNISSEUR';
    const ACTION_ADMIN_FOURNISSEUR_ACTION_DELETE = 'ACTION_ADMIN_FOURNISSEUR_ACION_MDELETE_FOURNISSEUR';



    ////////Les Salaires

    const ACTION_ADMIN_SALAIRE_ACTION_INDEX = 'ACTION_ADMIN_SALAIRE_ACION_SALAIRE_MANAGEMENT';
    const ACTION_ADMIN_SALAIRE_ACTION_STORE = 'ACTION_ADMIN_SALAIRE_ACION_STORE_SALAIRE';
    const ACTION_ADMIN_SALAIRE_ACTION_UPDATE = 'ACTION_ADMIN_SALAIRE_ACION_UPDATE_SALAIRE';
    const ACTION_ADMIN_SALAIRE_ACTION_DELETE = 'ACTION_ADMIN_SALAIRE_ACION_MDELETE_SALAIRE';

    ////////Les Stocks

    const ACTION_ADMIN_STOCKS_ACTION_INDEX = 'ACTION_ADMIN_STOCKS_ACION_STOCKS_MANAGEMENT';
    const ACTION_ADMIN_STOCKS_ACTION_UPDATE = 'ACTION_ADMIN_STOCKS_ACION_UPDATE_STOCKS';
    const ACTION_ADMIN_STOCKS_ACTION_UPDATE_STOCK_AJAX = 'ACTION_ADMIN_STOCKS_ACION_UPDATE_STOCK_AJAX';

    ///// Autres
    ///
    const ACTION_PARAMETRES_ACTION_INDEX_PARAMETRES = 'ACTION_PARAMETRES_ACION_PARAMETRES_MANAGEMENT';
    const ACTION_PARAMETRES_ACTION_STORE = 'ACTION_PARAMETRES_ACION_STORES_PARAMETRES';

    ///emails

    const ACTION_ADMIN_EMAIL_ACTION_INDEX = 'ACTION_ADMIN_EMAIL_ACION_EMAIL_MANAGEMENT';
    const ACTION_ADMIN_EMAIL_ACTION_STORE = 'ACTION_ADMIN_EMAIL_ACION_STORE_EMAIL';
    const ACTION_ADMIN_EMAIL_ACTION_DESTROY = 'ACTION_ADMIN_EMAIL_ACION_DESTROY_EMAIL';


    /////GESTION DES VENTES


    const ACTION_VENTES_ACTION_INDEX_VENTES = 'ACTION_VENTES_ACION_INDEX_VENTES';
    const ACTION_VENTES_ACTION_CREATE_VENTE = 'ACTION_VENTES_ACION_CREATE_VENTES';
    const ACTION_VENTES_ACTION_CHANGE_STATE_VENTE = 'ACTION_VENTES_ACION_CHANGE_FACTURE_STATE_VENTE';
    const ACTION_VENTES_ACTION_FACTURE_VENTE = 'ACTION_VENTES_ACION_FACTURE_VENTE';
    const ACTION_VENTES_ACTION_LIST_CLIENTS_VENTE = 'ACTION_VENTES_ACION_LIST_CLIENTS_VENTE';
    const ACTION_VENTES_ACTION_LIST_VENTES = 'ACTION_VENTES_ACION_LIST_VENTES';
    const ACTION_VENTES_ACTION_DETAILS_VENTES = 'ACTION_VENTES_ACION_DETAILS_VENTES';
    const ACTION_VENTES_ACTION_STORE_VENTES = 'ACTION_VENTES_ACION_STORE_VENTES';
    const ACTION_VENTES_ACTION_LIST_PRODUIT_VENTES = 'ACTION_VENTES_ACION_LIST_PRODUIT_VENTES';

//GESTION  DES STOCKS

    const ACTION_STOCKS_ACTION_INDEX_STOCKS = 'ACTION_STOCKS_ACION_INDEX_STOCKS';
    const ACTION_STOCKS_ACTION_HISTORIQUE_STOCKS = 'ACTION_STOCKS_ACION_HISTORIQUE_STOCKS';
    const ACTION_STOCKS_ACTION_CHECK_STOCKS = 'ACTION_STOCKS_ACION_CHECK_STOCKS';
    const ACTION_STOCKS_ACTION_GET_STOCKS_AJAX = 'ACTION_STOCKS_ACION_GET_STOCKS_AJAX';
    const ACTION_STOCKS_ACTION_DETAILLER_PRODUIT_STOCK = 'ACTION_STOCKS_ACION_DETAILLER_PRODUIT_STOCK';
    const ACTION_VENTES_ACTION_LIST_FOURNISSEURS_VENTES = 'ACTION_VENTES_ACION_LIST_FOURNISSEURS_VENTES';



    //ACHATS
    const ACTION_ACHATS_ACTION_CREATE_ACHATS = 'ACTION_ACHATS_ACION_CREATE_ACHATS';
    const ACTION_ACHATS_ACTION_STORE_ACHATS = 'ACTION_ACHATS_ACION_STORE_ACHATS';
    const ACTION_ACHATS_ACTION_LISTE_ACHATS = 'ACTION_ACHATS_ACION_LISTE_ACHATS';
    const ACTION_ACHATS_ACTION_DETAILS_ACHATS = 'ACTION_ACHATS_ACION_DETAILS_ACHATS';


    // APROVISIONNEMENTS

    const ACTION_APPROVS_ACTION_CREATE_APPROVS = 'ACTION_APPROVS_ACION_CREATE_APPROVS';
    const ACTION_APPROVS_ACTION_STORE_APPROVS = 'ACTION_APPROVS_ACION_STORE_APPROVS';
    const ACTION_APPROVS_ACTION_LISTE_APPROVS = 'ACTION_APPROVS_ACION_LISTE_APPROVS';
    const ACTION_APPROVS_ACTION_DETAILS_APPROVS = 'ACTION_APPROVS_ACION_DETAILS_APPROVS';

//              GESTION DES RAPPORTS

    const ACTION_RAPPORTS_ACTION_INDEX_RAPPORTS = 'ACTION_RAPPORTS_ACION_INDEX_RAPPORTS';
    const ACTION_RAPPORTS_ACTION_VENTES_RAPPORTS = 'ACTION_RAPPORTS_ACION_VENTES_RAPPORTS';
    const ACTION_RAPPORTS_ACTION_STOCKS_RAPPORTS = 'ACTION_RAPPORTS_ACION_STOCKS_RAPPORTS';
    const ACTION_RAPPORTS_ACTION_STOCKS_RAPPORTS_AJAX = 'ACTION_RAPPORTS_ACION_STOCKS_RAPPORTS_AJAX';
    const ACTION_RAPPORTS_ACTION_SEND_RAPPORTS_VENTES = 'ACTION_RAPPORTS_ACION_SEND_RAPPORTS_VENTES';
    const ACTION_RAPPORTS_ACTION_SEND_RAPPORTS_STOCKS = 'ACTION_RAPPORTS_ACION_SEND_RAPPORTS_STOCKS';


}
